# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=500)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='media',
            old_name='id',
            new_name='idMedia',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='poster_name',
            new_name='mediaType',
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.User'),
            preserve_default=False,
        ),
    ]
